YummyFood/urls.py
from django.contrib import admin
from django.urls import path, include
from food import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('food/', include('food.urls', namespace='food')),
]

food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns = [
    path('pizza', views.pizzas, name='pizzas'),
    path('burger', views.burgers, name='burgers'),
    path('order', views.order, name='order'),
    path('success', views.success, name='success'),
    path('signup', views.signup, name='signup'),
    path('login', views.userLogin, name='login'),
    path('logout', views.userLogout, name='logout'),

]

food/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=120)
    priceM = models.DecimalField(max_digits=4, decimal_places=2)
    priceL = models.DecimalField(max_digits=4, decimal_places=2)
    pImage = models.URLField()


class Burger(models.Model):
    name = models.CharField(max_length=120)
    priceM = models.DecimalField(max_digits=4, decimal_places=2)
    priceL = models.DecimalField(max_digits=4, decimal_places=2)
    bImage = models.URLField()


class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    number = models.CharField(max_length=60)
    bill = models.DecimalField(max_digits=4, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    note = models.TextField(blank=True, null=True)


class Item(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    size = models.CharField(max_length=60)

food/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    email = forms.EmailField(max_length=100, required=True, help_text='Inform a valid email address')
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Pizza, Burger, Order, Item
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
from .forms import NewUserForm
from django.contrib import messages
import random
import json

# Create your views here.
def randomOrderNumber(length):
    sample = 'ABCDEFGH0123456789'
    numberO = ''.join((random.choice(sample) for i in range(length)))
    return numberO


def index(request):
    request.session.set_expiry(0)
    ctx = {'active_link': 'index'}
    return render(request, 'food/index.html', ctx)

@csrf_exempt
def order(request):
    request.session.set_expiry(0)
    if request.is_ajax():
        request.session['note'] = request.POST.get('note')
        request.session['order'] = request.POST.get('orders')
        orders = json.loads(request.session['order'])
        request.session['bill'] = request.POST.get('bill')
        randomNum = randomOrderNumber(6)

        while Order.objects.filter(number=randomNum).count() > 0:
            randomNum = randomOrderNumber(6)
        
        if request.user.is_authenticated:
            order = Order(customer=request.user, 
                            number=randomOrderNumber(6), 
                            bill=float(request.session['bill']),
                            note=request.session['note'])
            order.save()
            request.session['orderNum'] = order.number
            for article in orders:
                item = Item(
                    order = order,
                    name = article[0],
                    price = article[2],
                    size = article[1],
                )
                item.save()

    ctx = {'active_link': 'order'}
    return render(request, 'food/order.html', ctx)

def pizzas(request):
    request.session.set_expiry(0)
    pizzas = Pizza.objects.all()
    ctx = {'pizzas': pizzas, 'active_link': 'pizza'}
    print(pizzas)
    return render(request, 'food/pizza.html', ctx)

def burgers(request):
    request.session.set_expiry(0)
    burgers = Burger.objects.all()
    ctx = {'burgers': burgers, 'active_link': 'burger'}
    print(burgers)
    return render(request, 'food/burger.html', ctx)

def success(request):
    orderNum = request.session['orderNum']
    bill = request.session['bill']
    items = Item.objects.filter(order__number=orderNum)
    ctx = {'orderNum':orderNum, 'bill':bill, 'items':items}
    return render(request, 'food/success.html', ctx)

def signup(request):
    ctx = {}
    if request.POST:
        form = NewUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            ctx['form'] = form
    else:
        form = NewUserForm()
        ctx['form'] = form
    return render(request, 'food/signup.html', ctx)

def userLogin(request):
    if request.POST:
        username = request.POST.get('username')
        pwd = request.POST.get('password')
        user = authenticate(request, username=username, password=pwd)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.info(request, 'username and/or password are incorrect')
    ctx = {'active_link': 'login'}
    return render(request, 'food/login.html', ctx)

def userLogout(request):
    logout(request)
    return redirect('index')

food/templates/food/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="icon" type="image/png" href="https://img.icons8.com/cotton/40/000000/beefburger.png">

    <title>{% block title %} {% endblock %}</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'food/css/style.css' %}">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="https://img.icons8.com/cotton/40/000000/beefburger.png" alt="" class="logo"> YummyFood!
            </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynav" aria-controls="mynav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="mynav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link {% if active_link == 'index' %}active{% endif %}" aria-current="page" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if active_link == 'pizza' %}active{% endif %}" href="{% url 'food:pizzas' %}">Pizza</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if active_link == 'burger' %}active{% endif %}" href="{% url 'food:burgers' %}">Burgers</a>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
              <li class="nav-item mt-2">
                <h5 class="text-light pt-3 pr-3">Welcome {{ user.username }}</h5>
              </li>
              {% endif %}
              <li class="nav-item mt-3">
                <a href="{% url 'food:order' %}" class="nav-link {% if active_link == 'order' %}active{% endif %}"><img src="https://img.icons8.com/fluent/30/000000/shopping-cart.png" alt=""><span id="cart"></span></a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link"  href="{% url 'food:logout' %}">
                  <img class="bg-light ml-1 rounded-circle" src="https://img.icons8.com/windows/27/000000/user.png"><br>Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link {% if active_link == 'login' %}active{% endif %}" href="{% url 'food:login' %}">
                  <img class="bg-light ml-1 rounded-circle" src="https://img.icons8.com/windows/27/000000/user.png"><br>Login</a>
              </li>
              {% endif %}
            </ul>
           
          </div>
        </div>
    </nav>

    <div>
        {% block content %} {% endblock %}
    </div>



    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{% static 'food/js/main.js' %}"></script>
    <script src="{% static 'food/js/order.js' %}"></script>
    <script src="{% static 'food/js/burger.js' %}"></script>

</body>
</html>

food/templates/food/burger.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Burgers{% endblock %}

{% block content %}

    
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 text-center">
                <h2 class="title">Our Burgers</h2>
                <div class="row">
                    {% for burger in burgers %}
                    <div class="col-md-4 p-4 prod">
                        <img class="picture" src="{{ burger.bImage }}" alt="">
                        <h4 class="pt-3" id="bur{{ burger.id }}">{{ burger.name }}</h4>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="burger{{ burger.id }}" value="{{ burger.priceM }}" checked>
                                M: {{ burger.priceM }} $
                            </label>
                        </div>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="burger{{ burger.id }}" value="{{ burger.priceL }}">
                                L: {{ burger.priceL }} $
                            </label>
                        </div>
                        <div>
                            <button class="btn-info mt-3" onclick="addBurger('{{ burger.id }}')">Add to cart</button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4 order">
                <div class="bg-dark p-4 rounded text-light">
                    <h2 class="text-center">Order List</h2>
                    <ul id="bcart"></ul>
                    <h4 class="text-end" id="btotal">Total: 0 $</h4>
                </div>
            </div>
        </div>
    </div>

    
    
        
    <script src="{% static 'food/js/burger.js' %}"></script>

{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

    <div class="home">
        
    </div>

{% endblock %}

food/templates/food/login.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Login{% endblock %}

{% block content %}

    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6 p-4 bg-dark text-light text-center">
                <h3>Login</h3>
                <a href="{% url 'food:signup' %}">Signup</a>
                <form method="POST">
                    {% csrf_token %}
                    
                    <div class="form-group mt-3">
                        <input type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group mt-3">
                        <input type="password" name="password" placeholder="*******">
                    </div>      
                    
                    <button type="submit" class="btn-info mt-5">Login</button>
                    {% if messages %}
                        <ul class="pt-2 text-center">
                            {% for msg in messages %}
                            <li style="color: red;">{{ msg }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>

{% endblock %}

food/templates/food/order.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Orders{% endblock %}

{% block content %}

    <div class="container-fluid m-4">
        <div class="row">
            {% if user.is_authenticated %}
            <h2>Welcome {{ user.username }}</h2>
            {% endif %}
            <div class="col-md-7 text-center">
                <h2>Order</h2>
                <div class="row">
                    <div class="col-md-3" id="name">
                        <h3>Name</h3>
                    </div>

                    <div class="col-md-3" id="size">
                        <h3>Size</h3>
                    </div>

                    <div class="col-md-3" id="price">
                        <h3>Price</h3>
                    </div>
                    <div class="col-md-1" id="rm">

                    </div>        
                </div>
                <h2 id="total">Total:</h2>
            </div>

            <div class="col-md-5 mt-4">
                <h2 class="mb-4">Message</h2>
                <textarea name="message" id="message" cols="40" rows="5"></textarea>
                {% if user.is_authenticated %}
                <div class="ml-auto m-4">
                    <button type="submit" class="btn-success" onclick="order()">Submit</button>
                </div>
                {% else %}
                <div class="ml-auto m-4">
                    <button class="btn-success"><a href="{% url 'food:login' %}" class="text-light" style="text-decoration: none;">Login</a></button>
                </div>
                {% endif %}
            </div>
        </div>
    </div>



    <script src="{% static 'food/js/cart.js' %}"></script>

{% endblock %}

food/templates/food/pizza.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Pizzas{% endblock %}

{% block content %}

    
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 text-center">
                <h2 class="title">Our Pizzas</h2>
                <div class="row">
                    {% for pizza in pizzas %}
                    <div class="col-md-4 p-4">
                        <img class="picture" src="{{ pizza.pImage }}" alt="">
                        <h4 class="pt-3" id="piz{{ pizza.id }}">{{ pizza.name }}</h4>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="pizza{{ pizza.id }}" value="{{ pizza.priceM }}" checked>
                                M: {{ pizza.priceM }} $
                            </label>
                        </div>
                        <div class="form-check-inline">
                            <label class="form-check-label">
                                <input type="radio" class="form-check-input" name="pizza{{ pizza.id }}" value="{{ pizza.priceL }}">
                                L: {{ pizza.priceL }} $
                            </label>
                        </div>
                        <div>
                            <button class="btn-info mt-3" onclick="addPizza('{{ pizza.id }}')">Add to cart</button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4 order">
                <div class="bg-dark p-4 rounded text-light">
                    <h2 class="text-center">Order List</h2>
                    <ul id="pcart"></ul>
                    <h4 class="text-end" id="ptotal">Total: 0 $</h4>
                </div>
            </div>
        </div>
    </div>

    
    
        
    <script src="{% static 'food/js/order.js' %}"></script>

{% endblock %}

food/templates/food/signup.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}SignUp{% endblock %}

{% block content %}

    <div class="container-fluid p-5">
        <div class="row formal">
            <div class="col-md-3"></div>
            <div class="col-md-6 p-4 bg-dark text-light text-center">
                <h3>SignUp</h3>
                <a href="{% url 'food:login' %}" class="p-2">Login</a>
                <form method="POST">
                    {% csrf_token %}
                    
                    {% for field in form %}
                    <div class="form-group">
                        <div>
                            {{ field.label_tag }}
                        </div>
                        <div class="m-3">
                            {{ field }}
                        </div>
                        {% if field.help_text %}
                            <small style="color: grey;">{{ field.help_text }}</small>
                        {% endif %}
                        
                    </div>   
                    {% endfor %}
                    <div>
                        {% for error in form.errors %}
                            <small style="color: red;">{{ error }}</small>
                        {% endfor %}
                    </div>
                    <button type="submit" class="btn-info mt-5">SignUp</button>
                </form>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>

{% endblock %}

food/templates/food/success.html
{% extends 'food/base.html' %}

{% load static %}

{% block title %}Success{% endblock %}

{% block content %}

    <div class="container-fluid">
        <h2>We have received your order</h2>
        <h4>Number of order: {{ orderNum }}</h4>
        <h4>You have ordered:</h4>
        {% for item in items %}
        <h4>{{ item.name }} {{ item.size }} {{ item.price }}</h4>
        {% endfor %}
        <h4>Total: {{ bill }} $</h4>
        <h4>If you want to modify your order, please call us</h4>
        <h4>Phone: 0907-448-7865</h4>
    </div>

{% endblock %}